[font]
normal = { family = "Inconsolata Nerd Font", style = "Regular" }
bold = { family = "Inconsolata Nerd Font", style = "Bold" }
italic = { family = "Inconsolata Nerd Font", style = "Italic" }
bold_italic = { family = "Inconsolata Nerd Font", style = "Bold Italic" }
size = 16.0
